import re

def convert_mysql_to_postgres(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Remove MySQL specific headers/footers
    content = re.sub(r'SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";', '', content)
    content = re.sub(r'START TRANSACTION;', '', content)
    content = re.sub(r'SET time_zone = "\+00:00";', '', content)
    content = re.sub(r'/\*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT \*/;', '', content)
    content = re.sub(r'/\*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS \*/;', '', content)
    content = re.sub(r'/\*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION \*/;', '', content)
    content = re.sub(r'/\*!40101 SET NAMES utf8mb4 \*/;', '', content)
    
    # 2. Quote Handling: Backticks to Double Quotes
    content = content.replace("`", '"')

    # 3. Data Types Cleaning
    # int(11) -> INTEGER
    content = re.sub(r'int\(\d+\)', 'INTEGER', content)
    # tinyint(1) -> BOOLEAN (or SMALLINT, usually boolean in mysql dumps)
    # Using SMALLINT to be safe as postgres doesn't auto-cast boolean form 0/1 always in inserts
    content = re.sub(r'tinyint\(\d+\)', 'SMALLINT', content)
    # bigint(20) -> BIGINT
    content = re.sub(r'bigint\(\d+\)', 'BIGINT', content)
    
    # unsigned -> removed (postgres doesn't have unsigned types generally, usually fits in signed or next size up)
    content = re.sub(r'UNSIGNED', '', content, flags=re.IGNORECASE)

    # 4. Table Definitions
    # Remove ENGINE=InnoDB ...
    content = re.sub(r'\) ENGINE=InnoDB.*?;', ');', content)
    
    # AUTO_INCREMENT -> SERIAL logic is complex in regex replacement.
    # Postgres uses sequences. A simple way for a dump import is to use "GENERATED BY DEFAULT AS IDENTITY" 
    # or just keep it as INTEGER and create sequence.
    # Better approach for simple converter:
    # Find "id INTEGER NOT NULL AUTO_INCREMENT" and replace with "id SERIAL PRIMARY KEY" 
    # But AUTO_INCREMENT is usually at the end of line in CREATE TABLE.
    
    # Let's clean AUTO_INCREMENT from column def
    content = re.sub(r'AUTO_INCREMENT', '', content, flags=re.IGNORECASE)
    
    # Fix Primary Keys defined at end
    # MySQL: PRIMARY KEY (`id`)
    # Postgres: CONSTRAINT pk_tablename PRIMARY KEY ("id") usually works, or inline.
    # The dump usually has "ALTER TABLE ... ADD PRIMARY KEY" at the end.
    
    # 5. Insert statements usually compatible if quotes are fixed (done in step 2).
    # MySQL: INSERT INTO "table" ("col") VALUES (1), (2);
    # Postgres: Same.

    # 6. Blob/Text
    # mediumtext -> text
    content = re.sub(r'mediumtext', 'TEXT', content, flags=re.IGNORECASE)
    # longtext -> text
    content = re.sub(r'longtext', 'TEXT', content, flags=re.IGNORECASE)
    
    # 7. Timestamp defaults
    # current_timestamp() -> current_timestamp
    content = content.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
    
    # 7. Timestamp defaults
    # current_timestamp() -> current_timestamp
    content = content.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
    
    # Remove ON UPDATE CURRENT_TIMESTAMP (Postgres doesn't support this in ALL cases merely in definition, needs trigger)
    content = re.sub(r'ON UPDATE CURRENT_TIMESTAMP', '', content, flags=re.IGNORECASE)

    # 9. Constraint/Index handling (Fixing ADD KEY syntax errors)
    
    # ADD UNIQUE KEY "name" (...) -> ADD CONSTRAINT "name" UNIQUE (...)
    content = re.sub(r'ADD UNIQUE KEY ["`]?(\w+)["`]?\s*\(', r'ADD CONSTRAINT "\1" UNIQUE (', content, flags=re.IGNORECASE)
    
    # ADD KEY "name" (...) -> Postgres doesn't support generic ADD INDEX in ALTER TABLE. 
    # Best to comment these out for a simple import, or convert to CREATE INDEX separately.
    # We comment them out.
    content = re.sub(r'(?<!PRIMARY )(?<!UNIQUE )ADD KEY ["`]?\w+["`]?\s*\(.*?\)', r'-- \g<0>', content, flags=re.IGNORECASE)
    
    # CRITICAL FIX: If we commented out an inner item (like ADD KEY), the *previous* line might end with a comma.
    # Postgres treats "ADD PK (id), -- comment" as an unfinished statement waiting for the next clause.
    # If the next clause is commented out, it fails.
    # We find ",\s*-- ADD KEY" and replace the comma with a semicolon to terminate the previous statement.
    content = re.sub(r',(\s*-- ADD KEY)', r';\1', content, flags=re.IGNORECASE)
    
    # 10. LOCK TABLES / UNLOCK TABLES
    content = re.sub(r'LOCK TABLES', '-- LOCK TABLES', content, flags=re.IGNORECASE)
    content = re.sub(r'UNLOCK TABLES', '-- UNLOCK TABLES', content, flags=re.IGNORECASE)

    # 11. MODIFY syntax (usually for AUTO_INCREMENT in dumps)
    # MySQL: ALTER TABLE ... MODIFY ...
    # This is problematic in Postgres.
    # Since we are using re.DOTALL, this matches multiple lines.
    # Using '-- ' only comments the first line. We need to use block comments /* ... */
    content = re.sub(r'ALTER TABLE ["`]?\w+["`]?\s+MODIFY .*?;', r'/* \g<0> */', content, flags=re.IGNORECASE | re.DOTALL)

    # 8. Escape characters
    # MySQL uses \' for escaped single quote. Postgres uses '' for escaped single quote within string.
    # This is tricky without parsing.
    # Simple heuristic: Replace \' with '' inside values. 
    # Warning: This might break if binary data is present. Assuming text dump.
    content = content.replace("\\'", "''")

    # Appending the NEW Inquiry Table Schema for Postgres
    new_table_sql = """
--
-- Table structure for table "inquiry" (New Feature)
--

CREATE TABLE IF NOT EXISTS "inquiry" (
  "id" SERIAL PRIMARY KEY,
  "customer" VARCHAR(100) NOT NULL,
  "email" VARCHAR(120) NOT NULL,
  "phone" VARCHAR(20) NOT NULL,
  "vehicle_interest" VARCHAR(100),
  "car_type" VARCHAR(20),
  "contact_method" VARCHAR(50),
  "notes" TEXT,
  "source" VARCHAR(50),
  "status" VARCHAR(50) DEFAULT 'Pending',
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
    content += "\n" + new_table_sql

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Conversion complete. Saved to {output_file}")


if __name__ == "__main__":
    convert_mysql_to_postgres('u134626675_parivar_motors.sql', 'parivar_postgres.sql')
